---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
          - name: my-app
            image: tbshelmacr.azurecr.io/devopspractical/my-app:latest  # Replace with your ACR login server and image
            ports:
            - containerPort: 3000
          imagePullSecrets:
          - name: myregistrykey   # Referencing the secret that was created above
