# Stage 1: Build Stage
FROM node:16 AS build

# Install git
RUN apt-get update && apt-get install -y git

# Set the working directory
WORKDIR /usr/src/app

# Clone the repository
RUN git clone https://github.com/swimlane/devops-practical.git .

# Install npm dependencies
RUN npm install

# Copy the .env.example file to .env
RUN cp .env.example .env

# Directly replace the MongoDB URL in the .env file
RUN sed -i "s|MONGODB_URL=.*|MONGODB_URL=mongodb://adminuser:adminpassword@4.188.92.101:27017/database?authSource=admin|g" .env

# Stage 2: Production Stage
FROM node:16-slim AS production

# Set the working directory
WORKDIR /usr/src/app

# Copy only necessary files from the build stage
COPY --from=build /usr/src/app .

# Expose the application's port (default is 3000)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
